openapi: "3.0.0"
info:
  version: 0.0.1
  title: Grand Pool API
  description: Grand Pool mining pool API
paths:
  /blockchains:
    get:
      summary: Get available blockchains list
      operationId: getBlockchains
      responses:
        '200':
          description: Blockchains list response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Blockchain'
  /prices:
    get:
      summary: Get pool blockchain coin price list
      operationId: getPrices
      responses:
        '200':
          description: Price list response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CoinPrice'
  /prices/{blockchain}:
    get:
      summary: Get blockchain coin price and markets
      operationId: getBlockchainPrice
      parameters:
        - $ref: "#/components/parameters/Blockchain"
      responses:
        '200':
          description: Blockchain coin price response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockchainCoinPrice'
  /pools/{blockchain}:
    get:
      summary: Get full pool data on blockchain
      operationId: getBlockchainPool
      parameters:
        - $ref: "#/components/parameters/Blockchain"
      responses:
        '200':
          description: 'Pool data response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Pool'
  /pools/{blockchain}/info:
    get:
      summary: Get pool info on blockchain
      operationId: getBlockchainPoolInfo
      parameters:
        - $ref: "#/components/parameters/Blockchain"
      responses:
        '200':
          description: 'Pool info response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoolInfo'
  /pools/{blockchain}/stats:
    get:
      summary: Get pool statistics on blockchain
      operationId: getBlockchainPoolStats
      parameters:
        - $ref: "#/components/parameters/Blockchain"
      responses:
        '200':
          description: 'Pool statistics response'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PoolStats'
  /pools/{blockchain}/slaves:
    get:
      summary: Get pool locations on blockchain
      operationId: getBlockchainPoolSlaves
      parameters:
        - $ref: "#/components/parameters/Blockchain"
      responses:
        '200':
          description: 'Pool location response'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PoolSlave'
components:
  parameters:
    Blockchain:
      name: blockchain
      in: path
      description: Pool blockchain
      required: true
      schema:
        type: string
  schemas:
    Blockchain:
      type: object
      required:
        - coin
        - name
        - ticker
        - atomic_unit
      properties:
        coin:
          type: string
        name:
          type: string
        ticker:
          type: string
        atomic_unit:
          type: integer
    Price:
      type: object
      required:
        - price
        - price_change_24h_percentage
      properties:
        price:
          type: number
          format: double
        price_change_24h_percentage:
          type: number
          format: double
    MarketPrice:
      allOf:
        - $ref: '#/components/schemas/Price'
        - type: object
          required:
            - ticker
          properties:
            ticker:
              type: string
    CoinPrice:
      allOf:
        - $ref: '#/components/schemas/Price'
        - type: object
          required:
            - coin
          properties:
            coin:
              type: string
    BlockchainCoinPrice:
      allOf:
        - $ref: '#/components/schemas/Price'
        - type: object
          required:
            - markets
          properties:
            markets:
              type: array
              items:
                $ref: '#/components/schemas/MarketPrice'
    PayoutMode:
      type: string
      enum:
        - pplns
        - prop
    PoolFee:
      type: object
      required:
        - fee
      properties:
        fee:
          type: number
          format: double
        solo_fee:
          type: number
          format: double
    PayoutsInfo:
      type: object
      required:
        - interval
      properties:
        interval:
          type: integer
        min_payout:
          type: integer
        max_payout:
          type: integer
    PoolInfo:
      type: object
      properties:
        blockchain:
          type: string
        host:
          type: string
        algos:
          type: array
          items:
            type: string
        payout_mode:
          $ref: '#/components/schemas/PayoutMode'
        solo:
          type: boolean
        fee: 
          $ref: '#/components/schemas/PoolFee'
        payouts_info:
          $ref: '#/components/schemas/PayoutsInfo'
        agents:
          type: array
          items:
            type: string
    PoolStats:
      required:
        - miners_count
        - hashrate
        - avg_hashrate
        - share_difficulty
      properties:
        miners_count:
          type: integer
        solo_miners_count:
          type: integer
        hashrate:
          type: string
        avg_hashrate:
          type: string
        solo_hashrate:
          type: string
        solo_avg_hashrate:
          type: string
        share_difficulty:
          type: integer
        solo_share_difficulty:
          type: integer
    PoolSlave:
      required:
        - region
        - host
        - tcp_port
        - ssl_port
        - connected_at
      properties:
        region:
          type: string
        host:
          type: string
        tcp_port:
          type: integer
        ssl_port:
          type: integer
        solo_port:
          type: integer
        connected_at:
          type: string
    Pool:
      type: object
      required:
        - info
        - stats
        - slaves
      properties:
        info: 
          $ref: '#/components/schemas/PoolInfo'
        stats:
          $ref: '#/components/schemas/PoolStats'
        slaves:
          type: array
          items:
            $ref: '#/components/schemas/PoolSlave'

